version: '3.8'

services:
    db:
        restart: always
        build: ./postgres
        container_name: sphinx_postgres
        env_file: 
            - postgres/database.env
        expose: 
            - 5432
        volumes:
            - database:/var/lib/postgresql/data/
        networks: 
            - sphinx_network
    
    redis:
        restart: always
        build: ./redis
        container_name: sphinx_redis
        expose:
            - 6379
        networks: 
            - sphinx_network
    
    web:
        restart: always
        build: 
            context: ./code
        container_name: sphinx_web
        command: sh -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./code/:/code/
            - ./static/:/static/
            - ./media/:/media/
        expose:
            - 8000
        ports: 
            - "54321:8000"
        depends_on: 
            - db
            - redis
        networks: 
            - sphinx_network

volumes:
    database:
    
networks: 
    sphinx_network:
