# Generated by Django 3.1.7 on 2021-05-08 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSphinx', '0005_auto_20210506_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='banned',
            field=models.ManyToManyField(blank=True, related_name='meetings_banned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meetings_attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
