# Generated by Django 3.1.7 on 2021-04-20 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSphinx', '0002_auto_20210420_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attendees_recording',
            field=models.ManyToManyField(blank=True, null=True, related_name='meetings_recording', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
