# Generated by Django 3.1.7 on 2021-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSphinx', '0004_auto_20210506_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
