DEBUG: TRUE # Switch this in production
SECRET_KEY: # Your secret key

DATABASE:
    HOST: '127.0.0.1'
    PORT: 5432
    NAME: themeetingsphinx
    USER: # Your password
    PASSWORD: # Your password

ALLOWED_HOSTS:
    - "localhost"
    - "127.0.0.1"
    - "db"

CORS_ORIGIN_WHITELIST:
    - "http://localhost:3000"
    - "frontend"

CHANNEL_LAYER:
    HOST: 'redis'
    PORT: '6379'

DEFAULT_PROFILE_PICTURE: https://i.stack.imgur.com/dr5qp.jpg
